version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: cubos_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cubos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cubos_network

networks:
  cubos_network:
    driver: bridge

volumes:
  postgres_data: 